/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as CollectionCollectionIdImport } from './routes/collection.$collectionId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => rootRoute,
} as any)

const CollectionCollectionIdRoute = CollectionCollectionIdImport.update({
    id: '/collection/$collectionId',
    path: '/collection/$collectionId',
    getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
    interface FileRoutesByPath {
        '/': {
            id: '/'
            path: '/'
            fullPath: '/'
            preLoaderRoute: typeof IndexImport
            parentRoute: typeof rootRoute
        }
        '/collection/$collectionId': {
            id: '/collection/$collectionId'
            path: '/collection/$collectionId'
            fullPath: '/collection/$collectionId'
            preLoaderRoute: typeof CollectionCollectionIdImport
            parentRoute: typeof rootRoute
        }
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    '/': typeof IndexRoute
    '/collection/$collectionId': typeof CollectionCollectionIdRoute
}

export interface FileRoutesByTo {
    '/': typeof IndexRoute
    '/collection/$collectionId': typeof CollectionCollectionIdRoute
}

export interface FileRoutesById {
    __root__: typeof rootRoute
    '/': typeof IndexRoute
    '/collection/$collectionId': typeof CollectionCollectionIdRoute
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath
    fullPaths: '/' | '/collection/$collectionId'
    fileRoutesByTo: FileRoutesByTo
    to: '/' | '/collection/$collectionId'
    id: '__root__' | '/' | '/collection/$collectionId'
    fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute
    CollectionCollectionIdRoute: typeof CollectionCollectionIdRoute
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    CollectionCollectionIdRoute: CollectionCollectionIdRoute,
}

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/collection/$collectionId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/collection/$collectionId": {
      "filePath": "collection.$collectionId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
